image: docker:stable-git

services:
    - docker:dind
    - postgres

variables:
    ARTIFACTS_DIR: $CI_PROJECT_DIR/artifacts
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DB: $POSTGRES_DB
    CLIENT_ID: $CLIENT_ID
    CLIENT_SECRET: $CLIENT_SECRET

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

stages:
    - test
    - deploy

before_script:
    - mkdir -p $ARTIFACTS_DIR

test:python:
    image: python:3.11
    stage: test
    script:
        - cd src
        - pip3 install --no-cache --upgrade pip setuptools
        - pip3 install -r requirements.txt
        - export DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
        - pytest .

deploy:docker:
    image: 
        name: docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
    services:
        - docker:dind
    stage: deploy
    dependencies:
        - test:python
    artifacts:
        expire_in: 1 day
        paths:
            - $ARTIFACTS_DIR/
    script:
        - docker compose version
        - docker compose up -d --build
