image: python:3.11

variables:
    ARTIFACTS_DIR: $CI_PROJECT_DIR/artifacts
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

stages:
    - build-test
    # - integration-test

before_script:
    - mkdir -p $ARTIFACTS_DIR
    - python3 --version ; pip3 --version  # For debugging
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate

build-test:docker:
    image: postgres:15.1-alpine
    variables:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
    stage: build-test
    artifacts:
        expire_in: 1 day
        paths:
            - $ARTIFACTS_DIR/
    script:
        - cd src
        - pip install -r requirements.txt
        - pytest .
