image: docker:stable-git

services:
    - docker:dind
    - postgres

variables:
    ARTIFACTS_DIR: $CI_PROJECT_DIR/artifacts
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DB: $POSTGRES_DB

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

stages:
    - test
    - deploy

before_script:
    - mkdir -p $ARTIFACTS_DIR

test:python:
    image: python:3.11
    stage: test
    script:
        - cd src
        - pip3 install --no-cache --upgrade pip setuptools
        - pip3 install -r requirements.txt
        - export DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
        - pytest .

deploy:docker:
    image: 
        name: docker:stable-git
    stage: deploy
    dependencies:
        - test:python
    artifacts:
        expire_in: 1 day
        paths:
            - $ARTIFACTS_DIR/
    script:
        - apk update && apk add --no-cache build-base git curl bash
        - curl -SL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        - chmod +x /usr/local/bin/docker-compose
        - docker-compose --version
        - docker-compose up -d --build
