image: docker:stable-git

services:
    - docker:dind

variables:
    ARTIFACTS_DIR: $CI_PROJECT_DIR/artifacts
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

stages:
    - build-test
    # - integration-test

before_script:
    - set -e
    - if [ "$CI_JOB_NAME" = "build-test:go" ]; then apk update && apk add --no-cache build-base git curl bash docker; fi
    - mkdir -p $ARTIFACTS_DIR

build-test:docker:
    image: postgres:15.1-alpine
    variables:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
    stage: build-test
    artifacts:
        expire_in: 1 day
        paths:
            - $ARTIFACTS_DIR/
    script:
        - cd src
        - export PYTHONUNBUFFERED=1
        - apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
        - python3 -m ensurepip
        - pip3 install --no-cache --upgrade pip setuptools
        - pip3 install -r requirements.txt
        - export DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@localhost/hello_fastapi_dev
        - docker run -d -e  POSTGRES_USER=hello_fastapi -e POSTGRES_PASSWORD=hello_fastapi -e POSTGRES_DB=hello_fastapi_dev -p 5432:5432 postgres:15.1-alpine
        - pytest .
