image: docker:stable-git

services:
    - docker:dind

variables:
    ARTIFACTS_DIR: $CI_PROJECT_DIR/artifacts
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip


stages:
    - build-test
    # - integration-test

before_script:
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - set -e
    - if [ "$CI_JOB_NAME" = "build-test:docker" ]; then apk update && apk add --no-cache build-base git curl bash docker; fi
    - mkdir -p $ARTIFACTS_DIR

build-test:docker:
    image: postgres:15.1-alpine
    variables:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
    stage: build-test
    artifacts:
        expire_in: 1 day
        paths:
            - $ARTIFACTS_DIR/
    script:
        - cd src
        - pip install -r requirements.txt
        - pytest .
